services:
  - type: web
    name: legal-chatbot-backend
    env: python
    region: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
